import { ArrowLeft, Play, RotateCcw, TimerReset, Volume2, VolumeX, WalletCards } from 'lucide-react';
import { useCallback, useEffect, useRef, useState, type ComponentType, type ReactNode } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useApp } from '../App';
import { AnimeCharacter, type AnimeCharacterId } from '../components/Prologue';
import { quests, type Quest, type QuestMode } from '../game/data';
import { useGameProgress } from '../game/progress';
import { useSound } from '../game/useSound';

type Phase = 'briefing' | 'playing' | 'result';
type RewardState = { status: 'loading' | 'ready' | 'error'; hash?: string; amount?: string; paid?: boolean; message?: string };
type Finish = (won: boolean, summary: string, score: number) => void;
type MiniGameProps = { onFinish: Finish; play: (sound: 'tap' | 'collect' | 'hit' | 'win' | 'boost' | 'dialogue') => void };
const questCompanions: Record<string, AnimeCharacterId> = { yori: 'yori', beam: 'beam', mika: 'mika', peep: 'suzume' };

function GameClock({ seconds, children }: { seconds: number; children: ReactNode }) {
  return <div className="quest-game-hud"><span><TimerReset size={15} /> 00:{String(seconds).padStart(2, '0')}</span>{children}</div>;
}

function CatChase({ onFinish, play }: MiniGameProps) {
  const [tiles, setTiles] = useState<Array<'empty' | 'cat' | 'laser'>>(['empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty', 'empty']);
  const [rescued, setRescued] = useState(0); const [danger, setDanger] = useState(0); const [seconds, setSeconds] = useState(32); const done = useRef(false);
  const finish = useCallback((won: boolean) => { if (!done.current) { done.current = true; onFinish(won, won ? 'All six cat drones are safe. Yori’s wrench is doing a tiny victory dance.' : 'The laser alley won this round. The cat drones have opinions.', rescued * 30); } }, [onFinish, rescued]);
  useEffect(() => { const cycle = window.setInterval(() => { const index = Math.floor(Math.random() * 9); const type = Math.random() < .72 ? 'cat' : 'laser'; setTiles(current => current.map((_, i) => i === index ? type : 'empty')); }, 720); return () => clearInterval(cycle); }, []);
  useEffect(() => { const timer = window.setInterval(() => setSeconds(value => { if (value <= 1) { window.setTimeout(() => finish(rescued >= 6), 0); return 0; } return value - 1; }), 1000); return () => clearInterval(timer); }, [finish, rescued]);
  const tap = (tile: 'empty' | 'cat' | 'laser', index: number) => { if (done.current || tile === 'empty') return; setTiles(current => current.map((value, i) => i === index ? 'empty' : value)); if (tile === 'cat') { setRescued(value => { const next = value + 1; if (next >= 6) window.setTimeout(() => finish(true), 0); return next; }); play('collect'); } else { setDanger(value => { const next = value + 1; if (next >= 3) window.setTimeout(() => finish(false), 0); return next; }); play('hit'); } };
  return <div className="mini-game cat-chase-game"><GameClock seconds={seconds}><b>RESCUES {rescued}/6</b><b className="danger">ZAPS {danger}/3</b></GameClock><div className="game-callout"><strong>LASER CAT CHASE</strong><span>Click only the cat drones. Do not boop a laser gate.</span></div><div className="cat-grid">{tiles.map((tile, index) => <button key={index} onClick={() => tap(tile, index)} className={`cat-tile ${tile}`} aria-label={tile === 'cat' ? 'Rescue cat drone' : tile === 'laser' ? 'Avoid laser' : 'Empty alley'}>{tile !== 'empty' && <i className="arcade-item-art" />}</button>)}</div><p className="mini-caption">Yori: “They are small, jet-powered, and emotionally expensive.”</p></div>;
}

function NoriSorter({ onFinish, play }: MiniGameProps) {
  const [piece, setPiece] = useState<'nori' | 'pantry'>('nori'); const [sorted, setSorted] = useState(0); const [mistakes, setMistakes] = useState(0); const [seconds, setSeconds] = useState(30); const done = useRef(false);
  const newPiece = () => setPiece(Math.random() < .62 ? 'nori' : 'pantry');
  const finish = useCallback((won: boolean) => { if (!done.current) { done.current = true; onFinish(won, won ? 'Twelve nori sheets survived the shrine wind. Chef Beam cries into a perfectly legal bowl.' : 'The pantry belt is jammed. Chef Beam is now speaking in dramatic italics.', sorted * 18); } }, [onFinish, sorted]);
  useEffect(() => { const timer = window.setInterval(() => setSeconds(value => { if (value <= 1) { window.setTimeout(() => finish(sorted >= 12), 0); return 0; } return value - 1; }), 1000); return () => clearInterval(timer); }, [finish, sorted]);
  const sort = (bin: 'nori' | 'pantry') => { const correct = bin === piece; if (correct) { setSorted(value => { const next = value + 1; if (next >= 12) window.setTimeout(() => finish(true), 0); return next; }); play('collect'); } else { setMistakes(value => { const next = value + 1; if (next >= 3) window.setTimeout(() => finish(false), 0); return next; }); play('hit'); } newPiece(); };
  const isNori = piece === 'nori';
  return <div className="mini-game nori-sorter-game"><GameClock seconds={seconds}><b>SORTED {sorted}/12</b><b className="danger">JAMS {mistakes}/3</b></GameClock><div className="game-callout"><strong>TORII NORI SORTER</strong><span>Identify the item, then send it to the correct shrine pantry bin.</span></div><div className="sorter-belt"><i className="belt-arrow">➜</i><button className={`mystery-piece ${piece}`} onClick={() => play('tap')}><span className="arcade-item-art" /><b>{isNori ? 'GLOWING SHEET' : 'SUSPICIOUS PANTRY ITEM'}</b></button><i className="belt-arrow">➜</i></div><div className="sort-bins"><button onClick={() => sort('nori')}><span className="bin-art nori-art" /><b>NORI BIN</b><small>Seaweed only</small></button><button onClick={() => sort('pantry')}><span className="bin-art pantry-art" /><b>PANTRY BIN</b><small>Everything else</small></button></div><p className="mini-caption">Chef Beam: “This is sorting. Not driving. Please read the labels.”</p></div>;
}

function DriftDuel({ onFinish, play }: MiniGameProps) {
  const [needle, setNeedle] = useState(50); const [sweetSpot, setSweetSpot] = useState(50); const [gates, setGates] = useState(0); const [scratches, setScratches] = useState(0); const [seconds, setSeconds] = useState(28); const done = useRef(false); const needleRef = useRef(50); const spotRef = useRef(50);
  const finish = useCallback((won: boolean) => { if (!done.current) { done.current = true; onFinish(won, won ? 'Eight flawless rain-gates. Mika has been forced to clap exactly once.' : 'A scratch on the Shinkansen route. Mika has written a poem about your disappointment.', gates * 30); } }, [gates, onFinish]);
  const steer = useCallback((amount: number) => { setNeedle(current => { const next = Math.max(6, Math.min(94, current + amount)); needleRef.current = next; play('tap'); return next; }); }, [play]);
  useEffect(() => { const keys = (event: KeyboardEvent) => { if (event.key === 'ArrowLeft' || event.key.toLowerCase() === 'a') steer(-8); if (event.key === 'ArrowRight' || event.key.toLowerCase() === 'd') steer(8); }; window.addEventListener('keydown', keys); return () => window.removeEventListener('keydown', keys); }, [steer]);
  useEffect(() => { const gateLoop = window.setInterval(() => { const clean = Math.abs(needleRef.current - spotRef.current) <= 12; if (clean) { setGates(value => { const next = value + 1; if (next >= 8) window.setTimeout(() => finish(true), 0); return next; }); play('collect'); } else { setScratches(value => { const next = value + 1; if (next >= 1) window.setTimeout(() => finish(false), 0); return next; }); play('hit'); } const nextSpot = 15 + Math.random() * 70; spotRef.current = nextSpot; setSweetSpot(nextSpot); }, 2600); return () => clearInterval(gateLoop); }, [finish, play]);
  useEffect(() => { const timer = window.setInterval(() => setSeconds(value => { if (value <= 1) { window.setTimeout(() => finish(gates >= 8 && scratches === 0), 0); return 0; } return value - 1; }), 1000); return () => clearInterval(timer); }, [finish, gates, scratches]);
  return <div className="mini-game drift-duel-game"><GameClock seconds={seconds}><b>GATES {gates}/8</b><b className="danger">SCRATCHES {scratches}/1</b></GameClock><div className="game-callout"><strong>SHINKANSEN DRIFT DUEL</strong><span>Keep Suzume’s steering needle inside Mika’s moving cyan sweet spot.</span></div><div className="drift-track"><div className="track-lines" /><div className="sweet-spot" style={{ left: `${sweetSpot}%` }} /><div className="drift-needle" style={{ left: `${needle}%` }}><i className="drift-rider-art" /></div><div className="track-label left">HARD LEFT</div><div className="track-label right">HARD RIGHT</div></div><div className="drift-controls"><button onClick={() => steer(-8)}>← DRIFT LEFT</button><button onClick={() => steer(8)}>DRIFT RIGHT →</button></div><p className="mini-caption">Mika: “A clean gate every 2.6 seconds. No pressure, rookie.”</p></div>;
}

function LanternMemory({ onFinish, play }: MiniGameProps) {
  const [sequence, setSequence] = useState<number[]>([]); const [input, setInput] = useState<number[]>([]); const [lit, setLit] = useState<number | null>(null); const [round, setRound] = useState(0); const [message, setMessage] = useState('P.E.E.P. is arranging the lanterns…'); const done = useRef(false); const showing = useRef(true);
  const finish = useCallback((won: boolean) => { if (!done.current) { done.current = true; onFinish(won, won ? 'P.E.E.P.’s lantern heist—sorry, science experiment—is a success.' : 'Wrong lantern. P.E.E.P. has vanished into the night, leaving only a tiny feather.', round * 35); } }, [onFinish, round]);
  const showSequence = useCallback((next: number[]) => { showing.current = true; setInput([]); setMessage('Watch the lantern constellation…'); next.forEach((lamp, index) => window.setTimeout(() => { setLit(lamp); window.setTimeout(() => setLit(null), 280); }, 430 + index * 600)); window.setTimeout(() => { showing.current = false; setMessage('Now repeat it. Tap the lanterns in order.'); }, 580 + next.length * 600); }, []);
  useEffect(() => { const first = [Math.floor(Math.random() * 4)]; setSequence(first); setRound(1); showSequence(first); }, [showSequence]);
  const tap = (lamp: number) => { if (showing.current || done.current) return; play('tap'); const nextInput = [...input, lamp]; const expected = sequence[nextInput.length - 1]; if (lamp !== expected) { play('hit'); finish(false); return; } setInput(nextInput); if (nextInput.length === sequence.length) { if (sequence.length >= 5) { play('win'); finish(true); return; } const nextSequence = [...sequence, Math.floor(Math.random() * 4)]; setSequence(nextSequence); setRound(nextSequence.length); play('collect'); window.setTimeout(() => showSequence(nextSequence), 650); } };
  return <div className="mini-game lantern-memory-game"><GameClock seconds={Math.max(0, 35 - round * 4)}><b>ROUND {round}/5</b><b className="memory-state">{showing.current ? 'WATCH' : 'REPEAT'}</b></GameClock><div className="game-callout"><strong>LANTERN MEMORY HEIST</strong><span>{message}</span></div><div className="lantern-board">{['AKAI', 'KIIRO', 'AOI', 'MURASAKI'].map((lantern, index) => <button key={lantern} className={`memory-lantern lamp-${index} ${lit === index ? 'lit' : ''}`} onClick={() => tap(index)}><span className="lantern-art" /><b>{lantern}</b></button>)}</div><p className="mini-caption">P.E.E.P.: “Coo. This is not a heist. Remember five lights. For science.”</p></div>;
}

const games: Record<QuestMode, ComponentType<MiniGameProps>> = { 'cat-chase': CatChase, 'nori-rush': NoriSorter, 'shinkansen-drift': DriftDuel, 'lantern-flight': LanternMemory };

export function QuestArcadePage() {
  const { questId } = useParams(); const quest = quests.find(item => item.id === questId); const navigate = useNavigate(); const { wallet, connect } = useApp(); const { progress, update } = useGameProgress(); const { soundOn, setSoundOn, play } = useSound();
  const [phase, setPhase] = useState<Phase>('briefing'); const [runKey, setRunKey] = useState(0); const [result, setResult] = useState<{ won: boolean; summary: string; score: number } | null>(null); const [completedQuest, setCompletedQuest] = useState<Quest | null>(null); const [reward, setReward] = useState<RewardState | null>(null);
  const finish = useCallback((won: boolean, summary: string, score: number) => {
    setPhase('result'); setResult({ won, summary, score }); play(won ? 'win' : 'hit');
    update(current => {
      const firstClear = Boolean(won && quest && current.acceptedQuests.includes(quest.id) && !current.completedQuests.includes(quest.id));
      if (firstClear && quest) setCompletedQuest(quest);
      return { runs: current.runs + 1, coins: current.coins + (won ? 115 + (firstClear ? 65 : 0) : 0), highScore: Math.max(current.highScore, score), completedQuests: firstClear && quest ? [...current.completedQuests, quest.id] : current.completedQuests, bestCombo: Math.max(current.bestCombo, score) };
    });
  }, [play, quest, update]);
  const claim = useCallback(async () => { if (!completedQuest) return; if (!wallet.address) { await connect(); return; } setReward({ status: 'loading' }); try { const { claimQuestReward } = await import('../lib/stellar'); const receipt = await claimQuestReward(wallet.address, completedQuest.id); setReward({ status: 'ready', ...receipt }); update(current => ({ questReceipts: { ...current.questReceipts, [completedQuest.id]: { hash: receipt.hash, amount: receipt.amount, paid: receipt.paid } } })); } catch (error) { setReward({ status: 'error', message: error instanceof Error ? error.message : 'Could not create the Testnet reward receipt.' }); } }, [completedQuest, connect, update, wallet.address]);
  useEffect(() => { if (phase === 'result' && result?.won && completedQuest && wallet.address && !progress.questReceipts[completedQuest.id] && !reward) void claim(); }, [claim, completedQuest, phase, progress.questReceipts, result?.won, reward, wallet.address]);
  if (!quest) return <div className="quest-page"><h1>That quest slipped into another dimension.</h1><Link to="/game/quests">Back to side quests</Link></div>;
  const Game = games[quest.mode]; const stored = progress.questReceipts[quest.id];
  const restart = () => { setResult(null); setCompletedQuest(null); setReward(null); setRunKey(value => value + 1); setPhase('playing'); };
  return <div className="quest-arcade-page"><header className="arcade-topbar"><Link to="/game/quests"><ArrowLeft size={18} /> Side quests</Link><div className="arcade-title"><span>ONE-OF-A-KIND ARCADE</span><b>{quest.arcadeTitle}</b></div><button onClick={() => setSoundOn(value => !value)} className="arcade-icon">{soundOn ? <Volume2 size={19} /> : <VolumeX size={19} />}</button></header><section className={`quest-mini-stage mode-${quest.mode}`} style={{ '--quest-bg': `url('/assets/${quest.stage}')` } as React.CSSProperties}><div className="quest-stage-wash" />
    {phase === 'briefing' && <div className="quest-brief"><span>{quest.character.toUpperCase()} PRESENTS</span><h1>{quest.arcadeTitle}</h1><p>{quest.briefing}</p><div><b>MECHANIC:</b> {quest.mode === 'cat-chase' ? 'Rescue cats in a reaction grid.' : quest.mode === 'nori-rush' ? 'Sort shrine pantry items into the right bins.' : quest.mode === 'shinkansen-drift' ? 'Steer into a moving drift sweet spot.' : 'Memorize and replay lantern sequences.'}</div><button className="arcade-button" onClick={() => setPhase('playing')}><Play size={17} fill="currentColor" /> Start this game</button></div>}
    {phase === 'playing' && <><Game key={runKey} onFinish={finish} play={play} /><aside className="quest-anime-companion"><AnimeCharacter who={questCompanions[quest.id]} mood={quest.id === 'mika' ? 'smug' : quest.id === 'beam' ? 'panic' : quest.id === 'yori' ? 'worry' : 'ready'} />{quest.id === 'peep' && <span className="peep-drone"><i>COO!</i></span>}</aside></>}
    {phase === 'result' && result && <div className={`quest-result ${result.won ? 'won' : 'lost'}`}><span>{result.won ? 'QUEST CLEAR' : 'TRY AGAIN'}</span><h1>{result.won ? 'That was a real game.' : 'The side quest wins… for now.'}</h1><p>{result.summary}</p><b className="quest-score">{result.score} arcade points</b>{completedQuest && <div className="quest-receipt">{stored || reward?.status === 'ready' ? <><b>{stored?.paid ?? reward?.paid ? 'Testnet XLM bounty sent!' : 'Testnet completion receipt saved.'}</b><span>{stored?.amount ?? reward?.amount} · <a href={`https://stellar.expert/explorer/testnet/tx/${stored?.hash ?? reward?.hash}`} target="_blank" rel="noreferrer">view hash ↗</a></span></> : reward?.status === 'loading' ? <><b>Sending the bounty receipt…</b><span>Talking to the Testnet treasury.</span></> : reward?.status === 'error' ? <><b>Reward needs a retry.</b><span>{reward.message}</span><button className="arcade-button receipt-action" onClick={() => void claim()}>Retry reward</button></> : !wallet.address ? <button className="arcade-button receipt-action" onClick={() => void connect()}><WalletCards size={16} /> Connect Freighter for bounty</button> : null}</div>}<div className="result-actions"><button className="arcade-button" onClick={restart}><RotateCcw size={17} /> Play again</button><button className="arcade-button secondary" onClick={() => navigate('/game/quests')}>More side quests</button></div></div>}
  </section></div>;
}
