import { ChevronLeft, ChevronRight, Music2, Volume2, VolumeX } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { AnimeCharacter } from '../components/Prologue';
import { mangaPages } from '../game/story-library';
import { useSound } from '../game/useSound';
import { useStoryAudio } from '../game/useStoryAudio';

export function StoryMangaPage() {
  const [index, setIndex] = useState(0); const active = mangaPages[index]; const { play: uiSound } = useSound(); const ambience = useStoryAudio();
  const chapters = useMemo(() => [...new Set(mangaPages.map(page => page.chapter))], []);
  useEffect(() => { if (ambience.enabled) ambience.play(active.sound); }, [active.sound, ambience]);
  const select = (next: number) => { uiSound('dialogue'); setIndex(Math.max(0, Math.min(mangaPages.length - 1, next))); };
  const toggleSound = () => { if (ambience.enabled) { ambience.stop(); ambience.setEnabled(false); } else { ambience.setEnabled(true); window.setTimeout(() => ambience.play(active.sound), 0); } };
  return <div className="story-library-page"><header className="story-library-head"><div><p>COMPLETE MANGA ARCHIVE</p><h1>Suzume’s Stellar Chronicle</h1><span>6 chapters · 12 illustrated pages · optional Web Audio soundscapes</span></div><button className={ambience.enabled ? 'on' : ''} onClick={toggleSound}>{ambience.enabled ? <Volume2 size={18} /> : <VolumeX size={18} />} {ambience.enabled ? 'Soundscape on' : 'Turn on story sound'}</button></header><div className="story-library-layout"><aside className="chapter-rail"><p>CHAPTERS</p>{chapters.map(chapter => { const page = mangaPages.find(item => item.chapter === chapter)!; const activeChapter = page.chapter === active.chapter; return <button key={chapter} className={activeChapter ? 'active' : ''} onClick={() => select(mangaPages.findIndex(item => item.chapter === chapter))}><b>0{chapter}</b><span>{page.chapterTitle}</span><small>pages {(chapter - 1) * 2 + 1}–{chapter * 2}</small></button>; })}<div className="sound-note"><Music2 size={15} /> The soundscape starts only after you enable it.</div></aside><section className="story-reader"><div className="story-page-meta"><span>CHAPTER 0{active.chapter} · {active.chapterTitle.toUpperCase()}</span><b>PAGE {String(active.page).padStart(2, '0')} / 12</b></div><article className="story-manga-canvas" style={{ '--story-bg': `url('/assets/${active.background}')` } as React.CSSProperties}><div className="story-manga-halftone" /><div className="story-stamp">{active.stamp}</div><div className="story-narration">{active.narration}</div><div className={`story-cast cast-${active.cast.length}`}>{active.cast.map((who, castIndex) => <div key={who} className={`story-cast-member member-${castIndex}`}><AnimeCharacter who={who} mood={active.lines.find(line => line.speaker === who)?.mood ?? 'watchful'} /></div>)}</div><div className="story-dialogue-stack">{active.lines.map((line, lineIndex) => <div key={`${line.speaker}-${lineIndex}`} className={`story-line line-${line.speaker}`}><b>{line.speaker === 'beam' ? 'CHEF BEAM' : line.speaker.toUpperCase()}</b><p>“{line.text}”</p></div>)}</div><footer><small>{active.title}</small><span>✦ STELLAR RAMEN RUN</span></footer></article><nav className="story-reader-controls"><button onClick={() => select(index - 1)} disabled={index === 0}><ChevronLeft size={18} /> Previous</button><div>{mangaPages.map((page, pageIndex) => <button key={page.page} className={pageIndex === index ? 'active' : ''} aria-label={`Go to page ${page.page}`} onClick={() => select(pageIndex)} />)}</div><button onClick={() => select(index + 1)} disabled={index === mangaPages.length - 1}>Next <ChevronRight size={18} /></button></nav></section></div></div>;
}
